# .github/workflows/send-bale-message.yml
name: Send Message to Bale Bot

on:
  push:
    branches: [ main ] # یا نام شاخه‌ای که استفاده می‌کنید، مثلاً master

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Call Cloudflare Function
        run: |
          curl -X GET "https://6da49007.coinsurf.pages.dev/send"
